apiVersion: v1
kind: ResourceQuota
metadata:
  name: crq-ns-kienld
  namespace: kienld
spec:
  hard:
    pods: '4'
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
    secrets: '10'                
    configmaps: '10'             
    persistentvolumeclaims: '5'  
    requests.storage: 50Gi        

