apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: crq-kienld
spec:
  quota:
    hard:
      count/buildconfigs.build.openshift.io: "87"
      services.nodeports: '0'
      secrets: '100'
      services.loadbalancers: '0'
      persistentvolumeclaims: '20'
      ephemeral-storage: 20Gi
      ac-bronze-single.storageclass.storage.k8s.io/requests.storage: 1800Gi
      pods: '100'
      requests.storage: 100Gi
      requests.memory: 20Gi
      requests.cpu: '2'
      limits.cpu: '10'
      limits.memory: 10
      configmaps: '100'
      services: '100'
  selector:
    labels: 
      kubernetes.io/metadata.name: kienld
