apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apps-admin-binding
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: app-user
    namespace: apps
roleRef:
  kind: Role
  name: apps-admin
  apiGroup: rbac.authorization.k8s.io
