apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  db_dsn: "root:Ol8PS96sF8@tcp(mysql.ac-devsecops.svc.cluster.local:3306)/todo-auth?charset=utf8mb4&parseTime=True&loc=Local"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  jwt_key: "jwt-fis-devsecops"
